### ISSUE TITLE
Transparency

### ISSUE THREAD

**Issue by Vampurica** [itsxScrubz/scrubz_hud#2]
Hey there,

I am really enjoying your hud, but I was wondering if you'd work on adding transparency as a new feature?
I tried to find a way to change the stroke for the bars to RGBA or enable alpha on the CTX somehow and failed.

Thanks

**Comment by itsxScrubz** [comment]
Yeah. I'm already working on a v2 with many many more features and 3-6 hud styles to allow users to choose from (not sure how many exactly yet) as well as being able to drag hud elements around to reposition.
